topics:
  -
    topic: /tf_static
    type: tf2_msgs/msg/TFMessage
    queue_size: 1
    qos:
      history: keep_all
      reliability: reliable
      durability: transient_local
  -
    topic: /map
    type: nav_msgs/msg/OccupancyGrid
    queue_size: 1
    qos:
      history: keep_all
      reliability: reliable
      durability: transient_local

services_1_to_2: []
services_2_to_1: []
